0;OK
3;Invalid Command.
7;Invalid Block Size.
8;Invalid Write.
9;Error Answer Block Size.
10;Not Allocat Memory.
11;Invalid Read.
22;Invalid Type.
23;Error in send_RR_data function.
24;Invalid IP.
25;Invalid BackPlane.
26;Invalid Slot.
27;Invalid Channel.
28;Invalid Remote Node Address.
31;Invalid Address.
32;Invalid Command.
33;Blank Station.
35;Error Micrologix Request.
38;Invalid Sub-Element.
39;Invalid Writing SubElement.
40;Invalid BCD.
41;Invalid Format.
42;Connection Error.
43;Invalid Octet.
44;Invalid Message ID.
45;Communication Error.
46;Invalid tag name
501;Program Not Found
502;Unknown Datatype
503;Unknown Member
504;Unknown Tag
505;Invalid Read Complete
506;Waiting For Another Station
507;Unexpected Error
508;Cache Synchronization Error
509;Program Changed
510;Invalid Cache Action settings
511;Invalid Memory Offset
1001;Malformed Enip Header
1002;Malformed Enip Data
1003;Device Error
1004;Wrong Sequence Number
1100;Invalid Session Handle
2001;Connection Failure
2004;Path Segment Error
2005;Invalid Path
2006;Partial Transfer
2601;Unrecognized Service Code
2602;Malformed Cip Header
2603;Malformed Cip Data
2604;Unexpected Response
2605;String too big