0;Ok
1;A field has an illegal value
2;Less levels specified in address than minimum for any address
3;More levels specified in address than system supports
4;Symbol not found
5;Symbol is of improper format
6;Address doesn't point to something usable
7;File is wrong size, check if the address requested is in the range configured in the PLC
8;Cannot complete request, situation has changed since the start of the command
9;Data or file is too large
10;Transaction size plus word address is too large, invalid Block Size for this CPU model
11;Access denied, improper privilege, PLC is likely to being downloaded a new program
12;Condition cannot be generated  resource is not available
13;Condition already exists  resource is already available
14;Command cannot be executed, check if the PLC family configured in the driver settings is correct.
15;Histogram overflow
16;No access
17;Illegal data type, check if the file that you are reading exists in the PLC and if the type matches.
18;Invalid parameter or invalid data
19;Address reference exists to deleted area
20;Command execution failure for unknown reason; possible PLC3 histogram overflow
21;Data conversion error
22;Scanner not able to communicate with 1771 rack adapter
23;Type mismatch
24;1771 module response was not valid
25;Duplicated label
26;File is open; another node owns it
27;Another node is the program owner, PLC is likely to being downloaded a new program
28;Reserved
29;Reserved
30;Data table element protection violation
31;Temporary internal problem
34;Remote rack fault
35;Timeout
36;Unknown error
256;Writing bit is not allowed via Write Trigger.
257;Write or Read bit on BCD or Float Type is not allowed.
258;Addressing problem or memory protect rungs.
259;Send file number error
260;PLC family is missconfigured
261;Protocol Error
65535;Error Sending DF1 message.