0;Ok
1;INVALID REQUEST
2;ILLEGAL DATA ADDRESS
3;ILLEGAL DATA VALUE
4;ILLEGAL RESPONSE LENGTH
5;ACKNOWLEDGE
6;SLAVE DEVlCE BUSY
7;NEGATlVE ACKNOWLEDGE
8;MEMORY PARlTY ERROR
10;Invalid Header
11;Invalid Address
12;Block size limit exceeded
13;Invalid CRC
18;Read an Invalid BCD Value
19;Try Write an invalid BCD Value
21;Error in retrieving or writing all the requested records from the File using Read File Record command
22;File Records are not supported on MDS and for write on Driver sheets
100;Illegal operation
