0;Ok
1;ILLEGAL FUNCTION
2;ILLEGAL DATA ADDRESS
3;ILLEGAL DATA VALUE
4;SLAVE DEVICE FAILURE
5;ACKNOWLEDGE
6;SLAVE DEVICE BUSY
7;NEGATIVE ACKNOWLEDGE
8;MEMORY PARITY ERROR
10;Invalid 'Header' field
11;Invalid 'Address' field
12;Invalid Block Size (too much registers per scan)
13;Invalid CheckSum
14;TCP/IP error
15;Invalid IP address
16;Connection Error
18;Read an Invalid BCD Value
19;Try Write an invalid BCD Value
20;Invalid Word Swap
22;Too many simultaneous requests for command 23
23;Read Block for command 23 should have fewer than 64 registers
24;Error in retrieving or writing all the requested records from the File using Read File Record command
25;File Records are not supported on MDS and for write on Driver sheets
100;Illegal operation
1005;Timeout Error
