0;Ok.
1;Error loading api
2;Error. Failed to publish to the topic
3;Error. Failed to subscribe to the topic(s)
4;Timeout connecting with the Broker
5;Error. Failed to connect with the Broker
6;Error create client instance
7;Invalid Station
8;Invalid address. Characters '+' and '#'are not accepted in address names
9;Invalid Header. Characters '+' and '#' are not accepted in header names
10;Mising SSL/TLS Certificate authentication
11;Invalid hexadecimal 
100;Illegal operation
1005;Timeout Error