0;OK 
1;Invalid Unit
2;Fail to allocate memory
3;Invalid Answer
4;RX Buffer overflow
5;Invalid message size
6;Driver supports UDP or Serial connections
257;01-01 Local node not in NetWork
258;01-02 Token Time Out
259;01-03 Retries Failed
260;01-04 Too Many send frames
261;01-05 Node address range error
262;01-06 Node address duplication
513;02-01 Destination node not in network
514;02-02 Unit missing
515;02-03 Third node missing
516;02-04 Destination node busy
517;02-05 Response timeout
769;03-01 Communications controller error
770;03-02 CPU Unit error
771;03-03 Controler error
772;03-04 Unit number error
1025;04-01 Undefined command
1026;04-02 Not supported by model/version
1281;05-01 Destination address setting error
1282;05-02 No routing tables
1283;05-03 Routing table error
1284;05-04 Too many relays
4097;10-01 Command too long
4098;10-02 Command too short
4099;10-03 Elements/data don't match
4100;10-04 Command format error
4101;10-05 Header error
4353;11-01 Area classification missing
4354;11-02 Access size error
4355;11-03 Address range error
4356;11-04 Address range exceeded
4358;11-06 Program missing
4361;11-09 Relational error
4362;11-0A Duplicate data access
4363;11-0B Response too long
4364;11-0C Parameter error
8194;20-02 Protected
8195;20-03 Table missing
8196;20-04 Data missing
8197;20-05 Program missing
8198;20-06 File missing
8199;20-07 Data mismatch
8449;21-01 Read Only
8450;21-02 Protected
8451;21-03 Cannot register
8453;21-05 Program missing
8454;21-06 File missing
8455;21-07 File name already exists
8456;21-08 Cannot change
