1;Protocol error.
2;Blocksize error.
3;Invalid family.
10;Sequence error.
16;Ilegal Command or Format.
20;Invalid address
30;Invalid header
32;Host has a problem and will not communicate.
48;Remote node host is missing, disconnected, or shutdown.
50;Writing bit is not allowed via Write Trigger.
64;Host could not complete function due to hardware fault.
80;Addressing problem or memory protect rungs.
90;Error Commit.
96;Function not allowed due to command protection selection.
112;Processor is in Program mode.
128;Compatibility mode file missing or communication zone problem.
144;Remote node cannot buffer command.
150;Send file number error
176;Remote node problem due to download.
177;Write or Read bit on BCD or Float Type is not allowed.
330;Error Connecting.
65535;Error Sending DF1 message.